name: ios-deploy

on:
  push:
    branches:
      - deploy
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: "17.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.17.5"

      - name: Install fastlane and plugins
        run: |
          cd ios
          gem install bundler
          bundle install

      - name: Flutter build
        run: |
          flutter pub get
          flutter build ios --release --no-codesign

      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: install firebase-tools
        run: npm install -g firebase-tools

      # 2020-05-19時点のデフォルトを指定
      - name: Select Xcode version
        run: |
          cd ios
          sudo xcode-select -s '/Applications/Xcode_13.2.1.app'
          xcodebuild -version

      - name: Adhoc
        env:
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          SLACK_URL: ${{ secrets.SLACK_URL }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FASTLANE_USERNAME: ${{ secrets.FASTLANE_USERNAME }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          APPLE_APP_ID: "net.urban-theory.flutter-template"
          APPLE_TEAM_ID: "F946L3T4HH"
          APPLE_KEY_ID: ${{ secrets.APPLE_KEY_ID }}
          APPLE_ISSUER_ID: ${{ secrets.APPLE_ISSUER_ID }}
          APPLE_KEY_CONTENT: ${{ secrets.APPLE_KEY_CONTENT }}
        run: |
          cd ios
          bundle exec fastlane adhoc --verbose
